### ISSUE TITLE
Shorten test name in VS output, make it more relevant 

### ISSUE THREAD

**Issue by ornatwork** [deloitte-solvas/SlackerRunner#5]
Remove prefix namespace 

x.x.x.x.TestClass.TestFunction(rbFile: report_destination/report_destination_seed.rb)

To show instead
TestClass.TestFunction(rbFile: report_destination/report_destination_seed.rb)

or the way Slacker does it with other tests, such as Lib.Spec
"Given a SomeContext"."an array of objects is passed to the underlying sproc as a table"

**Comment by ornatwork** [comment]
And if no text has been set, then it should show something like this

bc.tf_Role_Settings_For_yyyyyy 
( returns an empty recordset when no explicit permission/restriction exists )

**Comment by jdshkolnik** [comment]
[There's an open issue at xunit.](https://github.com/xunit/xunit/issues/649) It seems there might be some workarounds.

**Comment by ornatwork** [comment]
Also there is another open issue for the VS xUnit runner [here](https://github.com/xunit/xunit/issues/682)

**Comment by ericwj** [comment]
Could also see this as an issue with VS? I mean, VS is duplicating lots of strings at least as long as it is showing Test Explorer grouped by assembly or class.

The issue from in my case, working in VS mostly, really is that the most relevant information is usually invisible because even on a 4k screen I always need more pixels horizontally.

**Comment by jdshkolnik** [comment]
@ericwj Are you suggesting that VS is the source of the issue or that VS is also affected by the issue? VS is definitely not where the problem begins.

**Comment by ericwj** [comment]
Depends what VS does to the data it receives - or better - what it could do, depending on what that data looks like. I do know VS knows about class names, projects and traits since that is what VS allows to be selected to group Test Explorer on.

And if you pick class, it'll show proper class names without namespaces, but the tests remain fully qualified type names, with the method name and arguments appended. If those are - to VS - actually opaque strings that Xunit coughs up, then this is an issue in Xunit.

The underlying issue however could anyhow be as simple as that the contract VS and Xunit adhere to is missing one or two properties in the data model - the namespace maybe, the actual method name, arguments probably, ... 

It'd be awesome if VS could be smarter about parameters as well. Maybe even group on method name and show the parameters in the tooltip under each other, things like that...

**Comment by jdshkolnik** [comment]
Someone [posted](https://github.com/xunit/xunit/issues/649#issuecomment-323690445) what seems to be a workaround.

**Comment by ericwj** [comment]
Pity to see this isn't being picked up.

I still find myself putting Test Explorer accross half my 4k screen regularly to try and distinguish between tests. The hover tooltip is useless as it just shows some kind of hash or whatever in braces after the fqtn. I didn't write that. Why is it at all visible?

**Comment by jdshkolnik** [comment]
@ericwj Agreed. We will be doing something for this as soon as there's a bit of bandwidth but we're pretty slammed. If you have time, you're welcome to fork, apply that workaround, and submit a pull request.

**Comment by ornatwork** [comment]
@ericwj here https://github.com/xunit/xunit/issues/1454  is a discussion of the tooltip issue, they reported it to the MS VS group, you can vote it up.

**Comment by ornatwork** [comment]
This is possible as noted by [BradWilson](https://github.com/xunit/xunit/issues/682#issuecomment-171154428) at xunit in the issue we already referenced, it's built into xunit. You have to manually set the DisplayName yourself for your tests.  See in the image below how DisplayName can be used to override the default naming.
![test-names](https://user-images.githubusercontent.com/94155/30756019-f2a4f14a-9f85-11e7-8e32-bfbdb7139712.jpg)

**Comment by ornatwork** [comment]
@ericwj  @jdshkolnik with the new SlackerRunnerFact and SlackerRunnerTheory classes issue #21.  You can just rename your tests attribute in your code from [Fact] to [SlackerRunnerFact] same for Theory.  This way the naming of the tests in the VS and CI explorers will be fixed for you.  Available in SlackerRunner version 2.4.0.1+

**Comment by ericwj** [comment]
Well thanks @ornatwork but I seriously don't want to depend on SlackerRunner. Ruby is the kind of poor hack on Windows I try to avoid. MSSQL is also over the top.

I'm usually right now just declare tests with something like `[Fact(DisplayName = nameof(TestMethod))]` instead.
